import { BadRequestException, HttpException, HttpStatus, Inject, Injectable, UnauthorizedException } from '@nestjs/common';
import { createHash, randomBytes } from 'node:crypto';
import { PrismaService } from '../core/prisma.service.js';
import { BookingCodeService } from '../core/booking-code.service.js';
import { createCustomerOtpProvider, CustomerOtpProvider, OtpPurpose, OtpRegistration } from './otp-provider.js';

const SESSION_MS=30*24*60*60*1000;const GENERIC='Jika data dapat diproses, OTP telah dikirim.';
export const normalizeEmail=(v:string)=>v.trim().toLowerCase();
export function normalizePhone(v:string){let x=v.replace(/\D/g,'');if(x.startsWith('0'))x=`62${x.slice(1)}`;if(!x.startsWith('62'))x=`62${x}`;if(!/^62\d{8,13}$/.test(x))throw new BadRequestException('Nomor WhatsApp tidak valid');return x}
@Injectable()
export class CustomerAuthService{
  readonly otp:CustomerOtpProvider=createCustomerOtpProvider();private attempts=new Map<string,{count:number;at:number}>();
  constructor(@Inject(PrismaService) private p:PrismaService,@Inject(BookingCodeService) private codes:BookingCodeService){}
  private async tenant(){const t=await this.p.tenant.findUnique({where:{slug:process.env.PUBLIC_TENANT_SLUG??'batam-travelling'}});if(!t)throw new BadRequestException('Website belum terhubung ke tenant');return t}
  private limit(key:string,max=5){const now=Date.now(),x=this.attempts.get(key);if(!x||now-x.at>15*60_000){this.attempts.set(key,{count:1,at:now});return}if(x.count>=max)throw new HttpException('Terlalu banyak permintaan. Coba kembali dalam 15 menit.',HttpStatus.TOO_MANY_REQUESTS);x.count++}
  async requestRegistration(input:OtpRegistration,ip:string){const email=normalizeEmail(input.email),phone=normalizePhone(input.phone);if(!input.acceptedTerms)throw new BadRequestException('Persetujuan Syarat & Ketentuan diperlukan');this.limit(`register:${ip}:${email}`);const t=await this.tenant();const existing=await this.p.customerAccount.findUnique({where:{tenantId_email:{tenantId:t.id,email}}});const issued=await this.otp.issue(email,'REGISTER',existing?undefined:{...input,fullName:input.fullName.trim(),email,phone});const expose=!existing&&process.env.NODE_ENV!=='production'&&process.env.CUSTOMER_AUTH_EXPOSE_LOCAL_OTP==='true';return{message:GENERIC,challengeId:issued.challengeId,expiresAt:issued.expiresAt,...(expose?{developmentOtp:issued.developmentOtp}:{})}}
  async requestLogin(emailRaw:string,ip:string){const email=normalizeEmail(emailRaw);this.limit(`login:${ip}:${email}`);const t=await this.tenant(),account=await this.p.customerAccount.findUnique({where:{tenantId_email:{tenantId:t.id,email}}});const issued=await this.otp.issue(email,'LOGIN');const expose=account&&process.env.NODE_ENV!=='production'&&process.env.CUSTOMER_AUTH_EXPOSE_LOCAL_OTP==='true';return{message:GENERIC,challengeId:issued.challengeId,expiresAt:issued.expiresAt,...(expose?{developmentOtp:issued.developmentOtp}:{})}}
  async verify(emailRaw:string,challengeId:string,otp:string,purpose:OtpPurpose){const email=normalizeEmail(emailRaw);this.limit(`verify:${challengeId}`,6);let verified;try{verified=await this.otp.verify(challengeId,email,otp,purpose)}catch{throw new UnauthorizedException('OTP tidak valid atau kedaluwarsa')}const t=await this.tenant();let account=await this.p.customerAccount.findUnique({where:{tenantId_email:{tenantId:t.id,email}}});if(purpose==='REGISTER'){const r=verified.registration;if(!r)throw new UnauthorizedException('OTP tidak valid atau kedaluwarsa');account=await this.p.$transaction(async tx=>{let customer=await tx.customer.findFirst({where:{tenantId:t.id,email:{equals:email,mode:'insensitive'},archivedAt:null}});if(!customer){const customerCode=await this.codes.nextCustomer(tx,t.id);customer=await tx.customer.create({data:{tenantId:t.id,customerCode,fullName:r.fullName,email,phone:r.phone,leadSource:'WEBSITE'}})}return tx.customerAccount.create({data:{tenantId:t.id,customerId:customer.id,email,passwordHash:'passwordless:otp'}})})}if(!account||!account.active)throw new UnauthorizedException('OTP tidak valid atau kedaluwarsa');return this.createSession(account.id)}
  private async createSession(accountId:string){const token=randomBytes(32).toString('base64url'),tokenHash=createHash('sha256').update(token).digest('hex'),expiresAt=new Date(Date.now()+SESSION_MS);await this.p.$transaction([this.p.customerSession.deleteMany({where:{accountId}}),this.p.customerSession.create({data:{accountId,tokenHash,expiresAt}}),this.p.customerAccount.update({where:{id:accountId},data:{lastLoginAt:new Date()}})]);return{token,expiresAt}}
  async session(token?:string){if(!token)throw new UnauthorizedException('Session pelanggan diperlukan');const hash=createHash('sha256').update(token).digest('hex'),s=await this.p.customerSession.findUnique({where:{tokenHash:hash},include:{account:{include:{customer:true}}}});if(!s||s.expiresAt<=new Date()||!s.account.active)throw new UnauthorizedException('Session pelanggan tidak valid');return{accountId:s.account.id,customerId:s.account.customerId,email:s.account.email,fullName:s.account.customer.fullName,expiresAt:s.expiresAt}}
  async logout(token?:string){if(token)await this.p.customerSession.deleteMany({where:{tokenHash:createHash('sha256').update(token).digest('hex')}});return{ok:true}}
  async bookings(token?:string){const me=await this.session(token),t=await this.tenant();return this.p.booking.findMany({where:{tenantId:t.id,OR:[{customerId:me.customerId},{customerClaims:{some:{tenantId:t.id,accountId:me.accountId}}}]},select:{id:true,bookingCode:true,packageName:true,travelDate:true,status:true,pax:true,totalAmount:true,paidAmount:true},orderBy:{createdAt:'desc'}})}
  async claim(token:string|undefined,bookingCode:string,email:string,phone:string){const me=await this.session(token),t=await this.tenant(),code=bookingCode.trim().toUpperCase(),normalizedEmail=normalizeEmail(email),normalizedPhone=normalizePhone(phone);if(normalizedEmail!==me.email)throw new BadRequestException('Data klaim booking tidak cocok');return this.p.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`customer-booking-claim:${t.id}:${code}`}))`;const booking=await tx.booking.findFirst({where:{tenantId:t.id,bookingCode:code},include:{customer:true}});let storedPhone='';try{storedPhone=normalizePhone(booking?.customer.phone??'')}catch{}const matches=booking&&normalizeEmail(booking.customer.email??'')===normalizedEmail&&storedPhone===normalizedPhone;if(!matches)throw new BadRequestException('Data klaim booking tidak cocok');await tx.customerBookingClaim.upsert({where:{accountId_bookingId:{accountId:me.accountId,bookingId:booking.id}},create:{tenantId:t.id,accountId:me.accountId,bookingId:booking.id},update:{verifiedAt:new Date()}});await tx.auditLog.create({data:{tenantId:t.id,actorId:null,action:'booking.claimed.customer',resourceType:'Booking',resourceId:booking.id,metadata:{accountId:me.accountId,customerId:me.customerId}}});return{claimed:true,bookingCode:booking.bookingCode}})}
}
