services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: batam_erp
      POSTGRES_USER: batam_erp
      POSTGRES_PASSWORD: batam_erp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

