import './styles.css';
import './work.css';
import './project-planner.css';
import './package-builder.css';
import './crm-pipeline.css';
import './employee-records.css';
import './employees/access-management.css';
import './archives/archives.css';
import './sales/quotations/quotation-print.css';
import './public-site.css';
import './public-commerce.css';
import './my-trip/portal.css';
import './brand-theme.css';
import './pos/pos.css';
import './operations/trips/trips.css';
import './operations/open-trips/open-trips.css';
import './operations/open-trips/open-trips-responsive.css';
import './content-hub.css';
import './content-studio.css';
import './website-enhancements.css';
import './asset-knowledge/asset-knowledge.css';
import './reports/report-center.css';
import './vendors/vendors.css';
import './website-navy.css';
import './branding-contact.css';
import './brand-palette.css';
import './package-public-detail.css';
import './clickable-packages.css';
import './package-cleanup.css';
import './package-pricing.css';
import './seo.css';
import './booking-channels.css';
import './promo-pricing.css';
import './trip-public.css';
import './addons.css';
import './checkout-addons.css';
import './schedule-cards.css';
import './related-packages.css';
import './brand-contrast.css';
import './hero-contrast.css';
import './navigation-refinement.css';
import './service-products.css';
import './erp-ui-unified.css';
import './crm-trip-improvements.css';
import './trip-confirmation.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AppShell } from '../components/app-shell';
const inter = Inter({ subsets: ['latin'], variable: '--font-sans', display: 'swap' });
export const metadata: Metadata = {metadataBase:new URL(process.env.NEXT_PUBLIC_SITE_URL??'https://batamtravelling.com'),title:{default:'Batam Travelling | Paket Wisata Batam, Singapore & Malaysia',template:'%s | Batam Travelling'},description:'Paket wisata dari Batam ke Singapore, Malaysia, dan Kepulauan Riau. Open trip, private trip, ferry, hotel, transportasi, dan tour guide.',applicationName:'Batam Travelling',keywords:['travel Batam','paket wisata Batam','open trip Singapore dari Batam','private trip Batam','tour Singapore'],authors:[{name:'Batam Travelling'}],creator:'Batam Travelling',publisher:'Batam Travelling',alternates:{canonical:'/'},openGraph:{type:'website',locale:'id_ID',siteName:'Batam Travelling',title:'Batam Travelling | Perjalanan Terencana dari Batam',description:'Open trip, private trip, dan paket perjalanan lengkap dari Batam.'},twitter:{card:'summary_large_image',title:'Batam Travelling',description:'Paket wisata dan Open Trip terencana dari Batam.'},robots:{index:true,follow:true}};
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="id" className={inter.variable}><body><AppShell>{children}</AppShell></body></html>; }
