import './styles.css';
import './design-tokens.css';
import './work.css';
import './project-planner.css';
import './crm-pipeline.css';
import './sales/quotations/quotation-print.css';
import './public-site.css';
import './public-shell.css';
import './public-pages.css';
import './public-commerce.css';
import './my-trip/portal.css';
import './operations/trips/trips.css';
import './operations/open-trips/open-trips.css';
import './website-enhancements.css';
import './asset-knowledge/asset-knowledge.css';
import './reports/report-center.css';
import './vendors/vendors.css';
import './branding-contact.css';
import './crm-trip-improvements.css';
import type { Metadata } from 'next';
import { AppShell } from '../components/app-shell';
export const metadata: Metadata = {metadataBase:new URL(process.env.NEXT_PUBLIC_SITE_URL??'https://batamtravelling.com'),title:{default:'Batam Travelling | Paket Wisata Batam, Singapore & Malaysia',template:'%s | Batam Travelling'},description:'Paket wisata dari Batam ke Singapore, Malaysia, dan Kepulauan Riau. Open trip, private trip, ferry, hotel, transportasi, dan tour guide.',applicationName:'Batam Travelling',keywords:['travel Batam','paket wisata Batam','open trip Singapore dari Batam','private trip Batam','tour Singapore'],authors:[{name:'Batam Travelling'}],creator:'Batam Travelling',publisher:'Batam Travelling',alternates:{canonical:'/'},openGraph:{type:'website',locale:'id_ID',siteName:'Batam Travelling',title:'Batam Travelling | Perjalanan Terencana dari Batam',description:'Open trip, private trip, dan paket perjalanan lengkap dari Batam.'},twitter:{card:'summary_large_image',title:'Batam Travelling',description:'Paket wisata dan Open Trip terencana dari Batam.'},robots:{index:true,follow:true}};
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <html lang="id"><body><AppShell>{children}</AppShell></body></html>; }
