export const publicDemoEnabled = process.env.NODE_ENV !== 'production' && process.env.NEXT_PUBLIC_PUBLIC_DEMO_MODE === 'true';

const departures = (id: string, month: number, seats: number, surcharge = 0) => [{
  id: `${id}-departure`, startsAt: `2026-${String(month).padStart(2, '0')}-18T01:00:00.000Z`, endsAt: `2026-${String(month).padStart(2, '0')}-20T11:00:00.000Z`,
  maxPax: 24, remainingPax: seats, meetingPoint: 'Batam Centre Ferry Terminal', status: 'OPEN', surchargeLabel: surcharge ? 'High season' : undefined, surchargeAmount: surcharge, surchargeBasis: 'PER_PAX',
}];

export const demoTrips = [
  { id:'trip-singapore-family',packageCode:'BTV-SG-3D2N',name:'Singapore Family Discovery',destination:'Singapore',kind:'OPEN_TRIP',durationDays:3,minPax:2,maxPax:24,publicDescription:'Tiga hari menikmati ikon Singapore dengan ritme nyaman untuk keluarga.',prices:[{category:'ADULT',sellingPrice:3290000},{category:'CHILD',sellingPrice:2890000},{category:'INFANT',sellingPrice:650000}],departures:departures('sg',9,8,250000),included:'Ferry pulang-pergi\nHotel 2 malam\nTransportasi dan tour guide\nSarapan',excluded:'Paspor dan kebutuhan pribadi\nMakan di luar itinerary',meetingPoint:'Batam Centre Ferry Terminal',importantInfo:'Paspor berlaku minimal 6 bulan.',itineraries:[{dayNumber:1,time:'07:00',title:'Ferry ke Singapore',location:'Batam Centre'},{dayNumber:1,time:'10:00',title:'Merlion & Marina Bay',location:'Singapore'},{dayNumber:2,time:'09:00',title:'Sentosa exploration',location:'Sentosa'},{dayNumber:3,time:'16:00',title:'Kembali ke Batam',location:'HarbourFront'}],gallery:[]},
  { id:'trip-malaysia-heritage',packageCode:'BTV-MY-4D3N',name:'Malaysia Heritage Journey',destination:'Kuala Lumpur & Malaka',kind:'OPEN_TRIP',durationDays:4,minPax:2,maxPax:24,publicDescription:'Kota modern, kuliner, dan kawasan warisan dalam satu perjalanan.',prices:[{category:'ADULT',sellingPrice:4190000},{category:'CHILD',sellingPrice:3690000},{category:'INFANT',sellingPrice:750000}],departures:departures('my',10,12),included:'Ferry dan bus wisata\nHotel 3 malam\nTour guide\nSarapan',excluded:'Pengeluaran pribadi\nMakan malam bebas',meetingPoint:'Batam Centre Ferry Terminal',importantInfo:'Jadwal dapat menyesuaikan kondisi imigrasi.',itineraries:[{dayNumber:1,time:'06:30',title:'Berangkat dari Batam',location:'Batam Centre'},{dayNumber:2,time:'09:00',title:'Kuala Lumpur city tour',location:'Kuala Lumpur'},{dayNumber:3,time:'10:00',title:'Malaka heritage walk',location:'Malaka'}],gallery:[]},
  { id:'trip-bintan-escape',packageCode:'BTV-BIN-2D1N',name:'Bintan Weekend Escape',destination:'Bintan',kind:'OPEN_TRIP',durationDays:2,minPax:2,maxPax:20,publicDescription:'Akhir pekan ringkas untuk pantai, kuliner, dan landmark Bintan.',prices:[{category:'ADULT',sellingPrice:1790000},{category:'CHILD',sellingPrice:1490000},{category:'INFANT',sellingPrice:350000}],departures:departures('bin',9,5),included:'Transportasi\nHotel 1 malam\nTiket destinasi',excluded:'Aktivitas opsional\nKebutuhan pribadi',meetingPoint:'Pelabuhan Telaga Punggur',importantInfo:'Gunakan pakaian nyaman dan pelindung matahari.',itineraries:[{dayNumber:1,time:'08:00',title:'Berangkat ke Bintan',location:'Punggur'},{dayNumber:1,time:'10:00',title:'Lagoi & Treasure Bay',location:'Lagoi'},{dayNumber:2,time:'09:00',title:'Wisata kuliner',location:'Tanjung Pinang'}],gallery:[]},
  { id:'trip-batam-premium',packageCode:'BTV-BTM-1D',name:'Batam Premium Day Tour',destination:'Batam',kind:'PRIVATE_TRIP',durationDays:1,minPax:2,maxPax:12,publicDescription:'Private day tour fleksibel untuk keluarga atau tamu perusahaan.',prices:[{category:'ADULT',sellingPrice:890000},{category:'CHILD',sellingPrice:690000},{category:'INFANT',sellingPrice:0}],departures:[],included:'Mobil private\nDriver\nMakan siang seafood\nDokumentasi',excluded:'Tiket aktivitas tambahan',meetingPoint:'Hotel atau pelabuhan di Batam',importantInfo:'Tanggal dan rute dikonfirmasi bersama tim.',itineraries:[{dayNumber:1,time:'09:00',title:'Penjemputan',location:'Batam'},{dayNumber:1,time:'10:00',title:'Barelang & city highlights',location:'Batam'},{dayNumber:1,time:'18:00',title:'Pengantaran',location:'Batam'}],gallery:[]},
  { id:'trip-anambas-private',packageCode:'BTV-ANB-4D3N',name:'Anambas Private Island Escape',destination:'Kepulauan Anambas',kind:'PRIVATE_TRIP',durationDays:4,minPax:4,maxPax:10,publicDescription:'Perjalanan private untuk laut jernih, snorkeling, dan island hopping.',prices:[{category:'ADULT',sellingPrice:6890000},{category:'CHILD',sellingPrice:5690000},{category:'INFANT',sellingPrice:950000}],departures:[],included:'Penginapan 3 malam\nKapal island hopping\nMakan\nPeralatan snorkeling',excluded:'Tiket pesawat ke Letung\nAsuransi pribadi',meetingPoint:'Bandara Letung',importantInfo:'Cuaca laut dapat memengaruhi urutan itinerary.',itineraries:[{dayNumber:1,time:'12:00',title:'Tiba dan check-in',location:'Letung'},{dayNumber:2,time:'08:00',title:'Island hopping',location:'Anambas'},{dayNumber:3,time:'09:00',title:'Snorkeling',location:'Anambas'}],gallery:[]},
  { id:'trip-corporate-batam',packageCode:'BTV-CORP-3D2N',name:'Corporate Gathering Batam',destination:'Batam',kind:'PRIVATE_TRIP',durationDays:3,minPax:10,maxPax:80,publicDescription:'Program gathering yang dapat disesuaikan untuk tim perusahaan.',prices:[{category:'ADULT',sellingPrice:2590000},{category:'CHILD',sellingPrice:2190000},{category:'INFANT',sellingPrice:450000}],departures:[],included:'Hotel 2 malam\nMeeting room\nTransportasi\nGala dinner',excluded:'Tiket asal menuju Batam\nBranding khusus',meetingPoint:'Bandara Hang Nadim atau pelabuhan',importantInfo:'Proposal final mengikuti jumlah peserta dan kebutuhan acara.',itineraries:[{dayNumber:1,time:'14:00',title:'Arrival & team welcome',location:'Batam'},{dayNumber:2,time:'09:00',title:'Team building',location:'Nongsa'},{dayNumber:2,time:'19:00',title:'Gala dinner',location:'Batam'}],gallery:[]},
];

export const demoPromotions=[{id:'promo-family',code:'FAMILY10',title:'Liburan Keluarga Lebih Hemat',description:'Potongan 10% untuk paket Singapore Family Discovery pada jadwal pilihan.',discountType:'PERCENTAGE',discountValue:'10',endsAt:'2026-10-31T23:59:59.000Z',terms:'Berlaku untuk minimum 4 peserta. Tidak dapat digabung promo lain.',packages:[{package:{id:'trip-singapore-family',name:'Singapore Family Discovery',destination:'Singapore'}}]},{id:'promo-bintan',code:'WEEKENDBIN',title:'Weekend Bintan Bonus',description:'Potongan Rp150.000 per peserta untuk keberangkatan September.',discountType:'FIXED',discountValue:'150000',endsAt:'2026-09-30T23:59:59.000Z',terms:'Kuota promo terbatas.',packages:[{package:{id:'trip-bintan-escape',name:'Bintan Weekend Escape',destination:'Bintan'}}]}];
export const demoTickets=[{id:'ticket-ferry-sg',name:'Tiket Ferry Batam–Singapore',category:'TICKET',description:'Tiket pulang-pergi dengan jadwal terpilih.',price:890000,unit:'orang'},{id:'ticket-sea-aquarium',name:'S.E.A. Aquarium',category:'ATTRACTION',description:'Tiket atraksi untuk melengkapi perjalanan Singapore.',price:620000,unit:'orang'},{id:'ticket-snorkeling',name:'Paket Snorkeling Batam',category:'ACTIVITY',description:'Peralatan, kapal, dan pendamping lokal.',price:450000,unit:'orang'}];
export const demoTransportation=[{id:'transport-avanza',name:'Private Car Batam',category:'TRANSPORTATION',description:'Mobil dan driver hingga 10 jam.',price:850000,unit:'hari'},{id:'transport-hiace',name:'Hiace Group Transfer',category:'TRANSPORTATION',description:'Transfer grup hingga 14 peserta.',price:1450000,unit:'hari'},{id:'transport-airport',name:'Airport & Ferry Transfer',category:'TRANSPORTATION',description:'Penjemputan satu arah di area Batam.',price:250000,unit:'perjalanan'}];
export const demoArticles=[{slug:'panduan-liburan-singapore-dari-batam',title:'Panduan Liburan Singapore dari Batam',excerpt:'Persiapan ferry, imigrasi, transportasi, dan itinerary ringkas.',content:'Periksa masa berlaku paspor sebelum memesan perjalanan.\nDatang lebih awal ke terminal ferry agar proses check-in dan imigrasi tetap nyaman.\nPilih itinerary berdasarkan ritme keluarga, bukan hanya jumlah destinasi.',publishedAt:'2026-08-08T03:00:00.000Z',author:{name:'Tim Batam Travelling'},packages:[{package:{id:'trip-singapore-family',name:'Singapore Family Discovery',destination:'Singapore'}}]},{slug:'memilih-open-trip-atau-private-trip',title:'Open Trip atau Private Trip?',excerpt:'Kenali perbedaan biaya, fleksibilitas, dan pengalaman perjalanan.',content:'Open Trip cocok untuk jadwal tetap dan biaya yang lebih efisien.\nPrivate Trip memberi ruang lebih besar untuk menyesuaikan tanggal, ritme, dan kebutuhan peserta.\nPertimbangkan jumlah peserta, tujuan, serta kebutuhan khusus sebelum memilih.',publishedAt:'2026-08-05T03:00:00.000Z',author:{name:'Tim Batam Travelling'},packages:[{package:{id:'trip-batam-premium',name:'Batam Premium Day Tour',destination:'Batam'}}]}];
export const demoProfile={whatsappNumber:'6281277778899',contactEmail:'hello@batamtravelling.test',contactAddress:'Batam Centre, Kota Batam, Kepulauan Riau',contactHours:'Senin–Sabtu, 09.00–18.00 WIB',instagramUrl:'https://instagram.com/batamtravelling',customerTerms:'Harga dan ketersediaan dikonfirmasi saat pemesanan.\nData peserta harus sesuai dokumen perjalanan.',privacyPolicy:'Data pelanggan digunakan hanya untuk pemesanan, operasional perjalanan, dan komunikasi terkait.',cancellationPolicy:'Ketentuan pembatalan mengikuti paket dan jadwal yang dikonfirmasi pada quotation atau booking.'};

export function demoForPath(path:string):unknown|undefined{
  if(path==='/public/packages')return demoTrips;
  if(path.startsWith('/public/packages/'))return demoTrips.find(x=>x.id===decodeURIComponent(path.split('/').pop()||''));
  if(path==='/public/promotions')return demoPromotions;
  if(path==='/public/articles')return demoArticles;
  if(path.startsWith('/public/articles/'))return demoArticles.find(x=>x.slug===decodeURIComponent(path.split('/').pop()||''));
  if(path==='/public/company-profile')return demoProfile;
  if(path==='/public/service-products')return [...demoTickets,...demoTransportation];
}
