'use client';
import { FormEvent, useEffect, useState } from 'react';
import { apiGet, apiPatch, apiPost } from '../../../lib/api';

type Employee={id:string;name:string};
type Booking={id:string;bookingCode:string;packageName:string;travelDate:string;status:string;customer:{fullName:string};trip?:{id:string}};
type Trip={id:string;tripCode:string;title:string;status:string;startsAt:string;endsAt:string;vehicle?:string;booking:{bookingCode:string;pax:number;customer:{fullName:string}};assignments:{id:string;role:string;status:string;employee:{name:string;jobTitle?:string}}[]};
type PageResult<T>={items:T[];meta:{total:number}};
const nextStatus:Record<string,string|undefined>={DRAFT:'PLANNED',PLANNED:'READY',READY:'DEPARTED',DEPARTED:'ON_GOING',ON_GOING:'COMPLETED'};

export default function TripsPage(){
 const [rows,setRows]=useState<Trip[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[message,setMessage]=useState('');
 const load=async()=>{try{const[t,b,e]=await Promise.all([apiGet<PageResult<Trip>>('/trips?page=1&pageSize=100'),apiGet<PageResult<Booking>>('/bookings?page=1&pageSize=100&status=CONFIRMED'),apiGet<PageResult<Employee>>('/employees?page=1&pageSize=100')]);setRows(t.items);setBookings(b.items.filter(x=>!x.trip));setEmployees(e.items);setMessage('')}catch(error){setMessage((error as Error).message)}};
 useEffect(()=>{void load()},[]);
 async function createTrip(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);try{await apiPost('/trips',{bookingId:data.get('bookingId'),title:data.get('title')||undefined,startsAt:new Date(String(data.get('startsAt'))).toISOString(),endsAt:new Date(String(data.get('endsAt'))).toISOString(),meetingPoint:data.get('meetingPoint')||undefined,vehicle:data.get('vehicle')||undefined});form.reset();await load();setMessage('Trip operasional berhasil dibuat.')}catch(error){setMessage((error as Error).message)}}
 async function assign(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);try{await apiPost(`/trips/${data.get('tripId')}/assignments`,{employeeId:data.get('employeeId'),role:data.get('role'),taskNote:data.get('taskNote')||undefined});form.reset();await load();setMessage('Karyawan berhasil ditugaskan.')}catch(error){setMessage((error as Error).message)}}
 async function move(id:string,status:string){try{await apiPatch(`/trips/${id}/status`,{status});await load()}catch(error){setMessage((error as Error).message)}}
 return <main className="modulePage"><div className="moduleHeading"><div><p>OPERATIONS</p><h1>Trip & Assignment</h1><span>Trip dibuat dari booking yang sudah dikonfirmasi. Konflik jadwal karyawan diperiksa oleh API.</span></div><b>{rows.length} trip</b></div>
 <details className="createPanel"><summary>＋ Buat trip dari booking</summary><form className="moduleForm" onSubmit={createTrip}><select name="bookingId" required><option value="">Pilih booking confirmed</option>{bookings.map(x=><option key={x.id} value={x.id}>{x.bookingCode} · {x.customer.fullName} · {x.packageName}</option>)}</select><input name="title" placeholder="Judul trip (opsional)"/><label>Mulai<input name="startsAt" type="datetime-local" required/></label><label>Selesai<input name="endsAt" type="datetime-local" required/></label><input name="meetingPoint" placeholder="Meeting point"/><input name="vehicle" placeholder="Kendaraan"/><button>Buat trip</button></form></details>
 <details className="createPanel"><summary>＋ Tugaskan karyawan</summary><form className="moduleForm" onSubmit={assign}><select name="tripId" required><option value="">Pilih trip</option>{rows.filter(x=>!['COMPLETED','CANCELLED'].includes(x.status)).map(x=><option key={x.id} value={x.id}>{x.tripCode} · {x.title}</option>)}</select><select name="employeeId" required><option value="">Pilih karyawan</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="role" required>{['TRIP_LEADER','DRIVER','GUIDE','PHOTOGRAPHER','VIDEOGRAPHER','OPERATIONS','SALES_SUPPORT','OTHER'].map(x=><option key={x}>{x}</option>)}</select><input name="taskNote" placeholder="Catatan tugas"/><button>Simpan assignment</button></form></details>
 {message&&<p className={message.includes('berhasil')?'successText':'errorText'}>{message}</p>}<div className="dataTable"><div className="tableRow tableHead"><span>Trip</span><span>Customer</span><span>Jadwal</span><span>Tim & Status</span></div>
 {rows.map(x=><div className="tableRow" key={x.id}><span><b>{x.tripCode}</b><small>{x.title} · {x.booking.bookingCode}</small></span><span>{x.booking.customer.fullName}<small>{x.booking.pax} pax</small></span><span>{new Date(x.startsAt).toLocaleString('id-ID')}<small>s.d. {new Date(x.endsAt).toLocaleString('id-ID')}</small></span><span>{x.status}<small>{x.assignments.map(a=>`${a.employee.name} (${a.role} · ${a.status})`).join(', ')||'Belum ada assignment'}</small>{nextStatus[x.status]&&<button onClick={()=>void move(x.id,nextStatus[x.status]!)}>Lanjut ke {nextStatus[x.status]}</button>}</span></div>)}
 {!rows.length&&!message&&<p className="empty">Belum ada trip operasional.</p>}</div></main>
}
