import { BadRequestException, Body, Controller, Get, Inject, Injectable, Module, NotFoundException, Param, Patch, Post, Query, UseGuards } from '@nestjs/common';
import { PrismaService } from './core/prisma.service.js';
import { BookingCodeService } from './core/booking-code.service.js';
import { CurrentIdentity, IdentityGuard, PermissionGuard, Permissions, RequestIdentity } from './core/request-context.js';
import { AssignTripDto, BusinessReportQueryDto, CashflowQueryDto, CreateCashflowDto, ReverseFinancialEntryDto, CreateEmployeeDto, CreateProjectDto, CreateTaskDto, CreateTripDto, CreateVendorDto, PageQueryDto, TaskCommentDto, TransitionTripDto, UpdateAssignmentDto, UpdateEmployeeDto, UpdateProfileDto, UpdateProjectDto, UpdateTaskDto, UpdateVendorDto } from './connected-dto.js';
import { TripStatus } from '@prisma/client';
import { summarizeDepartureCapacity } from './core/departure-capacity-summary.js';

const taskInclude = { project: { include: { milestones: true } }, assignee: { select: { id: true, name: true } }, milestone: true, participants: { include: { user: { select: { id: true, name: true } } } }, comments: { include: { author: { select: { name: true } } }, orderBy: { createdAt: 'desc' as const }, take: 5 } };

@Injectable()
class ConnectedModulesService {
  constructor(@Inject(PrismaService) private readonly p: PrismaService,@Inject(BookingCodeService) private readonly codes:BookingCodeService) {}

  private page(q: PageQueryDto) { const page=Math.max(1,q.page??1),pageSize=Math.max(1,Math.min(100,q.pageSize??20));return{page,pageSize,skip:(page-1)*pageSize}; }
  private result<T>(items:T[],total:number,page:number,pageSize:number){return{items,meta:{page,pageSize,total,totalPages:Math.max(1,Math.ceil(total/pageSize))}}}
  async employees(i: RequestIdentity,q:PageQueryDto) { const x=this.page(q),search=q.search?.trim();const where={tenantId:i.tenantId,active:true,...(search?{OR:[{name:{contains:search,mode:'insensitive' as const}},{email:{contains:search,mode:'insensitive' as const}},{jobTitle:{contains:search,mode:'insensitive' as const}}]}:{})};const[total,items]=await Promise.all([this.p.user.count({where}),this.p.user.findMany({where,select:{id:true,employeeCode:true,name:true,email:true,phone:true,jobTitle:true,skills:true,availability:true,active:true,roles:{select:{roleId:true}}},orderBy:{name:'asc'},skip:x.skip,take:x.pageSize})]);return this.result(items,total,x.page,x.pageSize); }
  async projects(i: RequestIdentity,q:PageQueryDto) { const x=this.page(q),search=q.search?.trim();const where={tenantId:i.tenantId,...(search?{OR:[{code:{contains:search,mode:'insensitive' as const}},{name:{contains:search,mode:'insensitive' as const}},{description:{contains:search,mode:'insensitive' as const}}]}:{})};const[total,items]=await Promise.all([this.p.project.count({where}),this.p.project.findMany({where,include:{milestones:{orderBy:{dueDate:'asc'}}},orderBy:{updatedAt:'desc'},skip:x.skip,take:x.pageSize})]);return this.result(items,total,x.page,x.pageSize); }
  async trips(i: RequestIdentity,q:PageQueryDto) { const x=this.page(q),search=q.search?.trim();const where={tenantId:i.tenantId,...(search?{OR:[{tripCode:{contains:search,mode:'insensitive' as const}},{title:{contains:search,mode:'insensitive' as const}},{booking:{bookingCode:{contains:search,mode:'insensitive' as const}}}]}:{})};const[total,items]=await Promise.all([this.p.trip.count({where}),this.p.trip.findMany({where,include:{booking:{select:{bookingCode:true,pax:true,customer:{select:{fullName:true}}}},assignments:{include:{employee:{select:{name:true,jobTitle:true}}}}},orderBy:{startsAt:'asc'},skip:x.skip,take:x.pageSize})]);return this.result(items,total,x.page,x.pageSize); }
  async vendors(i: RequestIdentity,q:PageQueryDto) { const x=this.page(q),search=q.search?.trim();const where={tenantId:i.tenantId,status:'ACTIVE' as const,...(search?{OR:[{vendorCode:{contains:search,mode:'insensitive' as const}},{name:{contains:search,mode:'insensitive' as const}},{category:{contains:search,mode:'insensitive' as const}}]}:{})};const[total,items]=await Promise.all([this.p.vendor.count({where}),this.p.vendor.findMany({where,select:{id:true,vendorCode:true,name:true,category:true,status:true,contactName:true,phone:true,email:true,address:true,picEmployeeId:true,paymentTermsDays:true,notes:true},orderBy:{name:'asc'},skip:x.skip,take:x.pageSize})]);return this.result(items,total,x.page,x.pageSize); }
  async departures(i: RequestIdentity,q:PageQueryDto) { const x=this.page(q),search=q.search?.trim();const where={tenantId:i.tenantId,...(search?{package:{name:{contains:search,mode:'insensitive' as const}}}:{})};const[total,rows]=await Promise.all([this.p.packageDeparture.count({where}),this.p.packageDeparture.findMany({where,include:{package:{select:{id:true,name:true}},bookings:{where:{tenantId:i.tenantId,status:{notIn:['CANCELLED','REFUNDED']}},select:{pax:true}}},orderBy:{startsAt:'asc'},skip:x.skip,take:x.pageSize})]);const items=rows.map(({bookings,...departure})=>({...departure,...summarizeDepartureCapacity(departure.maxPax,bookings)}));return this.result(items,total,x.page,x.pageSize); }
  async tasks(i: RequestIdentity,q:PageQueryDto) { const x=this.page(q),search=q.search?.trim();const where={tenantId:i.tenantId,...(search?{OR:[{title:{contains:search,mode:'insensitive' as const}},{description:{contains:search,mode:'insensitive' as const}}]}:{})};const[total,items]=await Promise.all([this.p.task.count({where}),this.p.task.findMany({where,include:taskInclude,orderBy:{updatedAt:'desc'},skip:x.skip,take:x.pageSize})]);return this.result(items,total,x.page,x.pageSize); }

  async createEmployee(i:RequestIdentity,d:CreateEmployeeDto){const email=d.email.trim().toLowerCase();if(await this.p.user.findFirst({where:{tenantId:i.tenantId,email:{equals:email,mode:'insensitive'}},select:{id:true}}))throw new BadRequestException('Email karyawan sudah digunakan');const roleIds=[...new Set(d.roleIds??[])];if(roleIds.length&&await this.p.role.count({where:{id:{in:roleIds},OR:[{tenantId:i.tenantId},{tenantId:null}]}})!==roleIds.length)throw new BadRequestException('Role tidak valid');return this.p.$transaction(async tx=>{const employeeCode=await this.codes.nextEmployee(tx,i.tenantId);const user=await tx.user.create({data:{tenantId:i.tenantId,employeeCode,email,name:d.name.trim(),phone:d.phone,jobTitle:d.jobTitle,skills:d.skills,availability:d.availability}});if(roleIds.length)await tx.userRole.createMany({data:roleIds.map(roleId=>({userId:user.id,roleId}))});await tx.auditLog.create({data:{tenantId:i.tenantId,actorId:i.userId,action:'employee.created',resourceType:'User',resourceId:user.id,requestId:i.requestId,metadata:{employeeCode,roleIds}}});return user})}
  async updateEmployee(i:RequestIdentity,id:string,d:UpdateEmployeeDto){const current=await this.p.user.findFirst({where:{id,tenantId:i.tenantId}});if(!current)throw new NotFoundException('Karyawan tidak ditemukan');const email=d.email?.trim().toLowerCase();if(email&&await this.p.user.findFirst({where:{tenantId:i.tenantId,email:{equals:email,mode:'insensitive'},id:{not:id}},select:{id:true}}))throw new BadRequestException('Email karyawan sudah digunakan');const roleIds=d.roleIds?[...new Set(d.roleIds)]:undefined;if(roleIds?.length&&await this.p.role.count({where:{id:{in:roleIds},OR:[{tenantId:i.tenantId},{tenantId:null}]}})!==roleIds.length)throw new BadRequestException('Role tidak valid');return this.p.$transaction(async tx=>{const row=await tx.user.update({where:{id},data:{name:d.name?.trim(),email,phone:d.phone,jobTitle:d.jobTitle,skills:d.skills,availability:d.availability,active:d.active}});if(roleIds){await tx.userRole.deleteMany({where:{userId:id}});if(roleIds.length)await tx.userRole.createMany({data:roleIds.map(roleId=>({userId:id,roleId}))})}await tx.auditLog.create({data:{tenantId:i.tenantId,actorId:i.userId,action:'employee.updated',resourceType:'User',resourceId:id,requestId:i.requestId,metadata:{emailChanged:email!==undefined&&email!==current.email,rolesChanged:roleIds!==undefined,active:d.active??current.active}}});return row})}

  async createProject(i:RequestIdentity,d:CreateProjectDto){if(d.ownerId&&!await this.p.user.findFirst({where:{id:d.ownerId,tenantId:i.tenantId,active:true},select:{id:true}}))throw new BadRequestException('Owner proyek tidak valid');const startDate=d.startDate?new Date(d.startDate):undefined,dueDate=d.dueDate?new Date(d.dueDate):undefined;if(startDate&&dueDate&&dueDate<startDate)throw new BadRequestException('Tenggat proyek tidak boleh sebelum tanggal mulai');return this.p.$transaction(async tx=>{const row=await tx.project.create({data:{tenantId:i.tenantId,code:d.code.trim().toUpperCase(),name:d.name.trim(),description:d.description,status:d.status??'PLANNED',startDate,dueDate,ownerId:d.ownerId}});await tx.auditLog.create({data:{tenantId:i.tenantId,actorId:i.userId,action:'project.created',resourceType:'Project',resourceId:row.id,requestId:i.requestId,metadata:{code:row.code,ownerId:d.ownerId??null}}});return row})}
  async updateProject(i:RequestIdentity,id:string,d:UpdateProjectDto){const current=await this.p.project.findFirst({where:{id,tenantId:i.tenantId}});if(!current)throw new NotFoundException('Proyek tidak ditemukan');if(d.ownerId&&!await this.p.user.findFirst({where:{id:d.ownerId,tenantId:i.tenantId,active:true},select:{id:true}}))throw new BadRequestException('Owner proyek tidak valid');const startDate=d.startDate?new Date(d.startDate):current.startDate,dueDate=d.dueDate?new Date(d.dueDate):current.dueDate;if(startDate&&dueDate&&dueDate<startDate)throw new BadRequestException('Tenggat proyek tidak boleh sebelum tanggal mulai');const code=d.code?.trim().toUpperCase();if(code&&await this.p.project.findFirst({where:{tenantId:i.tenantId,code,id:{not:id}},select:{id:true}}))throw new BadRequestException('Kode proyek sudah digunakan');return this.p.$transaction(async tx=>{const row=await tx.project.update({where:{id},data:{code,name:d.name?.trim(),description:d.description,status:d.status,startDate:d.startDate?startDate:undefined,dueDate:d.dueDate?dueDate:undefined,ownerId:d.ownerId}});await tx.auditLog.create({data:{tenantId:i.tenantId,actorId:i.userId,action:'project.updated',resourceType:'Project',resourceId:id,requestId:i.requestId,metadata:{fromStatus:current.status,toStatus:row.status}}});return row})}

  async createVendor(i:RequestIdentity,d:CreateVendorDto){if(d.picEmployeeId&&!await this.p.user.findFirst({where:{id:d.picEmployeeId,tenantId:i.tenantId,active:true},select:{id:true}}))throw new BadRequestException('PIC vendor tidak valid');return this.p.$transaction(async tx=>{const vendorCode=await this.codes.nextVendor(tx,i.tenantId);const row=await tx.vendor.create({data:{tenantId:i.tenantId,vendorCode,name:d.name.trim(),category:d.category.trim(),status:d.status??'ACTIVE',contactName:d.contactName,phone:d.phone,email:d.email?.trim().toLowerCase(),address:d.address,picEmployeeId:d.picEmployeeId,paymentTermsDays:d.paymentTermsDays??0,notes:d.notes}});await tx.auditLog.create({data:{tenantId:i.tenantId,actorId:i.userId,action:'vendor.created',resourceType:'Vendor',resourceId:row.id,requestId:i.requestId,metadata:{vendorCode,category:row.category,picEmployeeId:d.picEmployeeId??null}}});return row})}
  async updateVendor(i:RequestIdentity,id:string,d:UpdateVendorDto){const current=await this.p.vendor.findFirst({where:{id,tenantId:i.tenantId}});if(!current)throw new NotFoundException('Vendor tidak ditemukan');if(d.picEmployeeId&&!await this.p.user.findFirst({where:{id:d.picEmployeeId,tenantId:i.tenantId,active:true},select:{id:true}}))throw new BadRequestException('PIC vendor tidak valid');return this.p.$transaction(async tx=>{const row=await tx.vendor.update({where:{id},data:{name:d.name?.trim(),category:d.category?.trim(),status:d.status,contactName:d.contactName,phone:d.phone,email:d.email?.trim().toLowerCase(),address:d.address,picEmployeeId:d.picEmployeeId,paymentTermsDays:d.paymentTermsDays,notes:d.notes}});await tx.auditLog.create({data:{tenantId:i.tenantId,actorId:i.userId,action:'vendor.updated',resourceType:'Vendor',resourceId:id,requestId:i.requestId,metadata:{fromStatus:current.status,toStatus:row.status,picEmployeeId:row.picEmployeeId??null}}});return row})}

  async createTrip(i:RequestIdentity,d:CreateTripDto){const startsAt=new Date(d.startsAt),endsAt=new Date(d.endsAt);if(endsAt<=startsAt)throw new BadRequestException('Waktu selesai trip harus setelah waktu mulai');const booking=await this.p.booking.findFirst({where:{id:d.bookingId,tenantId:i.tenantId,status:{in:['CONFIRMED','IN_PREPARATION','READY']}},include:{trip:true}});if(!booking)throw new BadRequestException('Booking belum dikonfirmasi atau tidak valid');if(booking.trip)throw new BadRequestException('Booking sudah memiliki trip operasional');return this.p.$transaction(async tx=>{const tripCode=await this.codes.nextTrip(tx,i.tenantId);const trip=await tx.trip.create({data:{tenantId:i.tenantId,tripCode,bookingId:booking.id,title:d.title?.trim()||booking.packageName,status:'DRAFT',startsAt,endsAt,departure:d.departure,meetingPoint:d.meetingPoint,vehicle:d.vehicle,itinerary:d.itinerary,notes:d.notes}});await tx.auditLog.create({data:{tenantId:i.tenantId,actorId:i.userId,action:'trip.created',resourceType:'Trip',resourceId:trip.id,requestId:i.requestId,metadata:{bookingId:booking.id,tripCode}}});await tx.outboxEvent.create({data:{tenantId:i.tenantId,eventType:'trip.created',aggregateType:'trip',aggregateId:trip.id,payload:{event_id:crypto.randomUUID(),event_type:'trip.created',tenant_id:i.tenantId,actor_id:i.userId,aggregate_type:'trip',aggregate_id:trip.id,schema_version:1,booking_id:booking.id}}});return trip})}

  async transitionTrip(i:RequestIdentity,id:string,d:TransitionTripDto){const trip=await this.p.trip.findFirst({where:{id,tenantId:i.tenantId}});if(!trip)throw new NotFoundException('Trip tidak ditemukan');const transitions:Record<TripStatus,TripStatus[]>={DRAFT:['PLANNED','CANCELLED'],PLANNED:['READY','CANCELLED'],READY:['DEPARTED','CANCELLED'],DEPARTED:['ON_GOING','CANCELLED'],ON_GOING:['COMPLETED','CANCELLED'],COMPLETED:[],CANCELLED:[]};if(!transitions[trip.status].includes(d.status))throw new BadRequestException(`Transisi ${trip.status} ke ${d.status} tidak diizinkan`);if(d.status==='CANCELLED'&&!d.reason?.trim())throw new BadRequestException('Alasan wajib untuk membatalkan trip');return this.p.$transaction(async tx=>{const updated=await tx.trip.update({where:{id},data:{status:d.status,notes:d.reason?[trip.notes,`Status ${d.status}: ${d.reason.trim()}`].filter(Boolean).join('\n'):undefined}});await tx.auditLog.create({data:{tenantId:i.tenantId,actorId:i.userId,action:`trip.${d.status.toLowerCase()}`,resourceType:'Trip',resourceId:id,requestId:i.requestId,metadata:{fromStatus:trip.status,toStatus:d.status,reason:d.reason??null}}});return updated})}

  async assignTrip(i:RequestIdentity,tripId:string,d:AssignTripDto){const trip=await this.p.trip.findFirst({where:{id:tripId,tenantId:i.tenantId}});if(!trip)throw new NotFoundException('Trip tidak ditemukan');if(['COMPLETED','CANCELLED'].includes(trip.status))throw new BadRequestException('Trip sudah ditutup');if(!await this.p.user.findFirst({where:{id:d.employeeId,tenantId:i.tenantId,active:true},select:{id:true}}))throw new BadRequestException('Karyawan tidak valid');const startsAt=d.startsAt?new Date(d.startsAt):trip.startsAt,endsAt=d.endsAt?new Date(d.endsAt):trip.endsAt;if(endsAt<=startsAt)throw new BadRequestException('Jadwal assignment tidak valid');const conflict=await this.p.tripAssignment.findFirst({where:{tenantId:i.tenantId,employeeId:d.employeeId,status:{in:['ASSIGNED','CONFIRMED']},startsAt:{lt:endsAt},endsAt:{gt:startsAt}},select:{id:true}});if(conflict)throw new BadRequestException('Karyawan sudah memiliki assignment pada waktu yang sama');return this.p.$transaction(async tx=>{const row=await tx.tripAssignment.create({data:{tenantId:i.tenantId,tripId,employeeId:d.employeeId,role:d.role,startsAt,endsAt,taskNote:d.taskNote}});await tx.auditLog.create({data:{tenantId:i.tenantId,actorId:i.userId,action:'trip.assignment.created',resourceType:'TripAssignment',resourceId:row.id,requestId:i.requestId,metadata:{tripId,employeeId:d.employeeId,role:d.role}}});return row})}

  async updateAssignment(i:RequestIdentity,id:string,d:UpdateAssignmentDto){const assignment=await this.p.tripAssignment.findFirst({where:{id,tenantId:i.tenantId}});if(!assignment)throw new NotFoundException('Assignment tidak ditemukan');return this.p.$transaction(async tx=>{const row=await tx.tripAssignment.update({where:{id},data:{status:d.status}});await tx.auditLog.create({data:{tenantId:i.tenantId,actorId:i.userId,action:'trip.assignment.updated',resourceType:'TripAssignment',resourceId:id,requestId:i.requestId,metadata:{fromStatus:assignment.status,toStatus:d.status}}});return row})}

  async createTask(i: RequestIdentity, d: CreateTaskDto) {
    const project = await this.p.project.findFirst({ where: { id: d.projectId, tenantId: i.tenantId }, select: { id: true } });
    if (!project) throw new BadRequestException('Proyek tidak valid');
    const userIds = [...new Set([d.assigneeId, ...(d.participantIds ?? [])].filter(Boolean))] as string[];
    if (userIds.length && await this.p.user.count({ where: { id: { in: userIds }, tenantId: i.tenantId, active: true } }) !== userIds.length) throw new BadRequestException('Karyawan tidak valid');
    if(d.milestoneId&&!await this.p.projectMilestone.findFirst({where:{id:d.milestoneId,projectId:d.projectId,tenantId:i.tenantId},select:{id:true}}))throw new BadRequestException('Milestone tidak valid untuk proyek ini');
    return this.p.$transaction(async tx => {
      const task = await tx.task.create({ data: { tenantId: i.tenantId, projectId: d.projectId, title: String(d.title), description: d.description, assigneeId: d.assigneeId, milestoneId: d.milestoneId, priority: d.priority ?? 'NORMAL', startDate: d.startDate ? new Date(d.startDate) : undefined, dueDate: d.dueDate ? new Date(d.dueDate) : undefined } });
      if (d.participantIds?.length) await tx.taskParticipant.createMany({ data: d.participantIds.map((userId: string) => ({ tenantId: i.tenantId, taskId: task.id, userId })) });
      return tx.task.findUniqueOrThrow({ where: { id: task.id }, include: taskInclude });
    });
  }

  async updateTask(i: RequestIdentity, id: string, d: UpdateTaskDto) {
    const task = await this.p.task.findFirst({ where: { id, tenantId: i.tenantId } });
    if (!task) throw new NotFoundException('Task tidak ditemukan');
    return this.p.$transaction(async tx => {
      const updated = await tx.task.update({ where: { id }, data: { status: d.status, progress: d.progress, completedAt: d.status === 'DONE' ? new Date() : d.status ? null : undefined } });
      if (d.comment) await tx.taskComment.create({ data: { tenantId: i.tenantId, taskId: id, authorId: i.userId, message: String(d.comment), type: 'STATUS_CHANGE', statusFrom: task.status, statusTo: d.status } });
      return updated;
    });
  }

  async comment(i: RequestIdentity, id: string, d: TaskCommentDto) {
    if (!await this.p.task.findFirst({ where: { id, tenantId: i.tenantId }, select: { id: true } })) throw new NotFoundException('Task tidak ditemukan');
    return this.p.taskComment.create({ data: { tenantId: i.tenantId, taskId: id, authorId: i.userId, message: String(d.message), type: d.type ?? 'NOTE' } });
  }

  async cashflow(i: RequestIdentity, year: number, month: number) {
    const from = new Date(Date.UTC(year, month - 1, 1)), to = new Date(Date.UTC(year, month, 1));
    const entries = await this.p.financialEntry.findMany({ where: { tenantId: i.tenantId, transactionDate: { gte: from, lt: to } }, include: { project: { select: { name: true } }, trip: { select: { title: true } }, vendor: { select: { name: true } } }, orderBy: { transactionDate: 'desc' } });
    const income = entries.filter(x => x.direction === 'IN').reduce((s, x) => s + Number(x.amount), 0), expense = entries.filter(x => x.direction === 'OUT').reduce((s, x) => s + Number(x.amount), 0);
    const operational=entries.filter(x=>x.direction==='OUT'&&x.costType==='OPERATIONAL').reduce((s,x)=>s+Number(x.amount),0),fixed=entries.filter(x=>x.direction==='OUT'&&x.fixedCost).reduce((s,x)=>s+Number(x.amount),0);
    return { entries, summary: { income, expense, net: income - expense, incoming:income, outgoing:expense, balance:income-expense, operational, fixed } };
  }

  async createCashflow(i: RequestIdentity, d: CreateCashflowDto) { const refs=await Promise.all([d.projectId?this.p.project.findFirst({where:{id:d.projectId,tenantId:i.tenantId},select:{id:true}}):true,d.tripId?this.p.trip.findFirst({where:{id:d.tripId,tenantId:i.tenantId},select:{id:true}}):true,d.vendorId?this.p.vendor.findFirst({where:{id:d.vendorId,tenantId:i.tenantId},select:{id:true}}):true]);if(refs.some(x=>!x))throw new BadRequestException('Relasi proyek, trip, atau vendor tidak valid');return this.p.$transaction(async tx=>{const row=await tx.financialEntry.create({data:{tenantId:i.tenantId,recordedById:i.userId,origin:'MANUAL',status:'POSTED',direction:d.direction,costType:d.costType,category:d.category.trim(),description:d.description.trim(),amount:d.amount,transactionDate:new Date(d.transactionDate),reference:d.reference,fixedCost:d.fixedCost??false,notes:d.notes,projectId:d.projectId,tripId:d.tripId,vendorId:d.vendorId}});await tx.auditLog.create({data:{tenantId:i.tenantId,actorId:i.userId,action:'cashflow.created',resourceType:'FinancialEntry',resourceId:row.id,requestId:i.requestId,metadata:{direction:d.direction,amount:d.amount,costType:d.costType}}});return row}); }

  async reverseCashflow(i: RequestIdentity, id: string, d: ReverseFinancialEntryDto) {
    const reason=d.reason.trim();if(!reason)throw new BadRequestException('Alasan reversal wajib diisi');
    return this.p.$transaction(async tx=>{
      await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${`financial-entry:${id}`}))`;
      const entry=await tx.financialEntry.findFirst({where:{id,tenantId:i.tenantId}});
      if(!entry)throw new NotFoundException('Entri keuangan tidak ditemukan');
      if(entry.origin==='PAYMENT')throw new BadRequestException('Penerimaan dari payment harus dibatalkan melalui alur refund/payment');
      if(entry.reversalOfId)throw new BadRequestException('Entri reversal tidak dapat dibalik kembali');
      if(entry.status!=='POSTED')throw new BadRequestException('Entri sudah direversal atau belum diposting');
      const now=new Date();
      const reversal=await tx.financialEntry.create({data:{tenantId:i.tenantId,recordedById:i.userId,reversalOfId:entry.id,reversalReason:reason,origin:'MANUAL',status:'POSTED',direction:entry.direction==='IN'?'OUT':'IN',costType:entry.costType,category:entry.category,description:`Reversal: ${entry.description}`,amount:entry.amount,transactionDate:now,reference:entry.reference,fixedCost:entry.fixedCost,notes:reason,projectId:entry.projectId,tripId:entry.tripId,vendorId:entry.vendorId}});
      await tx.financialEntry.update({where:{id:entry.id},data:{status:'REVERSED',reversedById:i.userId,reversedAt:now}});
      await tx.auditLog.create({data:{tenantId:i.tenantId,actorId:i.userId,action:'cashflow.reversed',resourceType:'FinancialEntry',resourceId:entry.id,requestId:i.requestId,metadata:{reversalEntryId:reversal.id,reason,amount:Number(entry.amount),originalDirection:entry.direction}}});
      return{originalId:entry.id,reversal};
    });
  }

  async reconcileCashflow(i: RequestIdentity, year: number, month: number) {
    const from=new Date(Date.UTC(year,month-1,1)),to=new Date(Date.UTC(year,month,1));
    const [payments,automaticEntries]=await Promise.all([
      this.p.payment.findMany({where:{tenantId:i.tenantId,status:'VERIFIED',receivedAt:{gte:from,lt:to}},select:{id:true,paymentNumber:true,invoiceId:true,amount:true,financialEntry:{select:{id:true,paymentId:true,invoiceId:true,amount:true,direction:true,origin:true,status:true}}}}),
      this.p.financialEntry.findMany({where:{tenantId:i.tenantId,origin:'PAYMENT',transactionDate:{gte:from,lt:to}},select:{id:true,paymentId:true,amount:true,payment:{select:{paymentNumber:true,status:true}}}})
    ]);
    const issues:Array<Record<string,unknown>>=[];
    for(const payment of payments){const entry=payment.financialEntry;if(!entry){issues.push({type:'MISSING_LEDGER',paymentId:payment.id,paymentNumber:payment.paymentNumber});continue}if(entry.origin!=='PAYMENT'||entry.direction!=='IN'||entry.status!=='POSTED'||entry.paymentId!==payment.id||entry.invoiceId!==payment.invoiceId||Number(entry.amount)!==Number(payment.amount)){issues.push({type:'LEDGER_MISMATCH',paymentId:payment.id,paymentNumber:payment.paymentNumber,entryId:entry.id,paymentAmount:Number(payment.amount),ledgerAmount:Number(entry.amount),ledgerStatus:entry.status})}}
    for(const entry of automaticEntries){if(!entry.payment||entry.payment.status!=='VERIFIED')issues.push({type:'ORPHAN_LEDGER',entryId:entry.id,paymentId:entry.paymentId,paymentNumber:entry.payment?.paymentNumber,paymentStatus:entry.payment?.status})}
    return{period:`${year}-${String(month).padStart(2,'0')}`,ok:issues.length===0,summary:{verifiedPayments:payments.length,automaticEntries:automaticEntries.length,issues:issues.length},issues};
  }

  async report(i: RequestIdentity, q: BusinessReportQueryDto) {
    const year = Number(q.year), month = q.month ? Number(q.month) : undefined;
    const from = new Date(Date.UTC(year, month ? month - 1 : 0, 1)), to = new Date(Date.UTC(month ? year : year + 1, month ?? 0, 1));
    const bp=Math.max(1,Number(q.bookingPage||1)),bps=Math.max(1,Math.min(100,Number(q.bookingPageSize||10))),pp=Math.max(1,Number(q.paymentPage||1)),pps=Math.max(1,Math.min(100,Number(q.paymentPageSize||10)));
    const bookingWhere={tenantId:i.tenantId,createdAt:{gte:from,lt:to}},paymentWhere={tenantId:i.tenantId,receivedAt:{gte:from,lt:to}};
    const [bookings,payments,bookingTotals,paymentCount,receivedTotals] = await Promise.all([
      this.p.booking.findMany({where:bookingWhere,select:{createdAt:true,bookingCode:true,packageName:true,travelDate:true,pax:true,status:true,totalAmount:true,paidAmount:true,customer:{select:{fullName:true,phone:true}}},orderBy:{createdAt:'desc'},skip:(bp-1)*bps,take:bps}),
      this.p.payment.findMany({where:paymentWhere,select:{receivedAt:true,paymentNumber:true,method:true,status:true,amount:true,customer:{select:{fullName:true}},invoice:{select:{invoiceNumber:true}},receivedBy:{select:{name:true}}},orderBy:{receivedAt:'desc'},skip:(pp-1)*pps,take:pps}),
      this.p.booking.aggregate({where:bookingWhere,_count:{_all:true},_sum:{pax:true,totalAmount:true}}),
      this.p.payment.count({where:paymentWhere}),
      this.p.payment.aggregate({where:{...paymentWhere,status:'VERIFIED'},_sum:{amount:true}}),
    ]);
    const bs = bookings.map(x => ({ tanggal: x.createdAt, kode: x.bookingCode, pelanggan: x.customer.fullName, telepon: x.customer.phone, paket: x.packageName, tanggalTrip: x.travelDate, pax: x.pax, status: x.status, total: Number(x.totalAmount), dibayar: Number(x.paidAmount) }));
    const ps = payments.map(x => ({ tanggal: x.receivedAt, nomor: x.paymentNumber, invoice: x.invoice.invoiceNumber, pelanggan: x.customer.fullName, metode: x.method, status: x.status, jumlah: Number(x.amount), diterimaOleh: x.receivedBy?.name ?? '-' }));
    const bookingCount=bookingTotals._count._all,invoiced=Number(bookingTotals._sum.totalAmount??0),received=Number(receivedTotals._sum.amount??0);
    return { period: month ? `${year}-${String(month).padStart(2,'0')}` : String(year), summary:{bookingCount,pax:Number(bookingTotals._sum.pax??0),bookingValue:invoiced,invoiced,received,outstanding:Math.max(0,invoiced-received),paymentCount},bookings:bs,payments:ps,bookingsMeta:{page:bp,pageSize:bps,total:bookingCount,totalPages:Math.max(1,Math.ceil(bookingCount/bps))},paymentsMeta:{page:pp,pageSize:pps,total:paymentCount,totalPages:Math.max(1,Math.ceil(paymentCount/pps))} };
  }

  async profile(i: RequestIdentity) { return this.p.companyProfile.findUnique({ where: { tenantId: i.tenantId } }); }
  async updateProfile(i: RequestIdentity, d: UpdateProfileDto) {
    const allowed = ['vision','mission','coreValues','customerTerms','privacyPolicy','cancellationPolicy','websiteLogoUrl','erpLogoUrl','documentLogoUrl','homepageSections','heroTitle','heroSubtitle','heroImageUrl','heroBadge','heroCtaPrimary','heroCtaSecondary','featureHeadline','featureText','howToBookTitle','howToBookText','aboutTitle','aboutText','whatsappNumber','whatsappNumberSecondary','contactEmail','contactAddress','contactHours','instagramUrl','facebookUrl','tiktokUrl','youtubeUrl'];
    const input = d as Record<string, unknown>;
    const data = Object.fromEntries(allowed.filter(k => k in input).map(k => [k, input[k] || null]));
    const existing=await this.p.companyProfile.findUnique({where:{tenantId:i.tenantId},select:{id:true}});if(!existing&&(!d.vision?.trim()||!d.mission?.trim()))throw new BadRequestException('Vision dan mission wajib diisi saat membuat profil perusahaan');
    return this.p.companyProfile.upsert({ where: { tenantId: i.tenantId }, update: { ...data, revisedById: i.userId }, create: { tenantId: i.tenantId, vision: d.vision!.trim(), mission: d.mission!.trim(), ...data, revisedById: i.userId } });
  }
}
@UseGuards(IdentityGuard,PermissionGuard) @Controller() class ConnectedController {
  constructor(@Inject(ConnectedModulesService) private readonly s:ConnectedModulesService){}
  @Get('employees') @Permissions('employee.read') employees(@CurrentIdentity()i:RequestIdentity,@Query()q:PageQueryDto){return this.s.employees(i,q)}
  @Post('employees') @Permissions('employee.manage') createEmployee(@CurrentIdentity()i:RequestIdentity,@Body()d:CreateEmployeeDto){return this.s.createEmployee(i,d)}
  @Patch('employees/:id') @Permissions('employee.manage') updateEmployee(@CurrentIdentity()i:RequestIdentity,@Param('id')id:string,@Body()d:UpdateEmployeeDto){return this.s.updateEmployee(i,id,d)}
  @Get('projects') @Permissions('project.read') projects(@CurrentIdentity()i:RequestIdentity,@Query()q:PageQueryDto){return this.s.projects(i,q)}
  @Post('projects') @Permissions('project.manage') createProject(@CurrentIdentity()i:RequestIdentity,@Body()d:CreateProjectDto){return this.s.createProject(i,d)}
  @Patch('projects/:id') @Permissions('project.manage') updateProject(@CurrentIdentity()i:RequestIdentity,@Param('id')id:string,@Body()d:UpdateProjectDto){return this.s.updateProject(i,id,d)}
  @Get('trips') @Permissions('trip.read') trips(@CurrentIdentity()i:RequestIdentity,@Query()q:PageQueryDto){return this.s.trips(i,q)}
  @Post('trips') @Permissions('trip.manage') createTrip(@CurrentIdentity()i:RequestIdentity,@Body()d:CreateTripDto){return this.s.createTrip(i,d)}
  @Patch('trips/:id/status') @Permissions('trip.manage') transitionTrip(@CurrentIdentity()i:RequestIdentity,@Param('id')id:string,@Body()d:TransitionTripDto){return this.s.transitionTrip(i,id,d)}
  @Post('trips/:id/assignments') @Permissions('assignment.manage') assignTrip(@CurrentIdentity()i:RequestIdentity,@Param('id')id:string,@Body()d:AssignTripDto){return this.s.assignTrip(i,id,d)}
  @Patch('trip-assignments/:id') @Permissions('assignment.manage') updateAssignment(@CurrentIdentity()i:RequestIdentity,@Param('id')id:string,@Body()d:UpdateAssignmentDto){return this.s.updateAssignment(i,id,d)}
  @Get('vendors') @Permissions('vendor.read') vendors(@CurrentIdentity()i:RequestIdentity,@Query()q:PageQueryDto){return this.s.vendors(i,q)}
  @Post('vendors') @Permissions('vendor.manage') createVendor(@CurrentIdentity()i:RequestIdentity,@Body()d:CreateVendorDto){return this.s.createVendor(i,d)}
  @Patch('vendors/:id') @Permissions('vendor.manage') updateVendor(@CurrentIdentity()i:RequestIdentity,@Param('id')id:string,@Body()d:UpdateVendorDto){return this.s.updateVendor(i,id,d)}
  @Get('open-trips') @Permissions('trip.read') departures(@CurrentIdentity()i:RequestIdentity,@Query()q:PageQueryDto){return this.s.departures(i,q)}
  @Get('tasks') @Permissions('task.read') tasks(@CurrentIdentity()i:RequestIdentity,@Query()q:PageQueryDto){return this.s.tasks(i,q)}
  @Post('tasks') @Permissions('task.create') createTask(@CurrentIdentity()i:RequestIdentity,@Body()d:CreateTaskDto){return this.s.createTask(i,d)}
  @Patch('tasks/:id') @Permissions('task.update') updateTask(@CurrentIdentity()i:RequestIdentity,@Param('id')id:string,@Body()d:UpdateTaskDto){return this.s.updateTask(i,id,d)}
  @Post('tasks/:id/comments') @Permissions('task.update') comment(@CurrentIdentity()i:RequestIdentity,@Param('id')id:string,@Body()d:TaskCommentDto){return this.s.comment(i,id,d)}
  @Get('cashflow') @Permissions('payment.read') cashflow(@CurrentIdentity()i:RequestIdentity,@Query()q:CashflowQueryDto){return this.s.cashflow(i,q.year,q.month)}
  @Post('cashflow') @Permissions('payment.manage') createCashflow(@CurrentIdentity()i:RequestIdentity,@Body()d:CreateCashflowDto){return this.s.createCashflow(i,d)}
  @Post('cashflow/:id/reverse') @Permissions('payment.manage') reverseCashflow(@CurrentIdentity()i:RequestIdentity,@Param('id')id:string,@Body()d:ReverseFinancialEntryDto){return this.s.reverseCashflow(i,id,d)}
  @Get('cashflow/reconciliation') @Permissions('dashboard.owner') reconcileCashflow(@CurrentIdentity()i:RequestIdentity,@Query()q:CashflowQueryDto){return this.s.reconcileCashflow(i,q.year,q.month)}
  @Get('reports/business') @Permissions('dashboard.owner') report(@CurrentIdentity()i:RequestIdentity,@Query()q:BusinessReportQueryDto){return this.s.report(i,q)}
  @Get('asset-knowledge/profile') @Permissions('settings.read') profile(@CurrentIdentity()i:RequestIdentity){return this.s.profile(i)}
  @Patch('asset-knowledge/profile') @Permissions('settings.manage') updateProfile(@CurrentIdentity()i:RequestIdentity,@Body()d:UpdateProfileDto){return this.s.updateProfile(i,d)}
}
@Module({controllers:[ConnectedController],providers:[ConnectedModulesService,PrismaService,BookingCodeService,IdentityGuard,PermissionGuard]}) export class ConnectedModulesModule {}
