import{describe,expect,it,vi}from'vitest';import{AdminWorkspaceService}from'./admin-workspace.module.js';
const baseIdentity={tenantId:'10000000-0000-4000-8000-000000000001',userId:'20000000-0000-4000-8000-000000000001',requestId:'test'};
const identity=(...permissions:string[])=>({...baseIdentity,permissions:new Set(permissions)})as any;

describe('promotion security',()=>{
  it('prevents submitter self approval',async()=>{const actor=identity('content.approve'),p:any={promotion:{findFirst:vi.fn().mockResolvedValue({id:'p',tenantId:actor.tenantId,status:'DRAFT',approvalStatus:'PENDING_REVIEW',submittedById:actor.userId,packages:[{packageId:'30000000-0000-4000-8000-000000000001'}]})}};await expect(new AdminWorkspaceService(p).reviewPromotion(actor,'p',{action:'APPROVE'})).rejects.toThrow(/tidak boleh/)});
  it('allows a least-privilege content approver to reject with a note',async()=>{const actor=identity('content.approve'),tx:any={promotion:{update:vi.fn().mockResolvedValue({id:'p',status:'DRAFT',approvalStatus:'REJECTED'})},auditLog:{create:vi.fn()}},p:any={promotion:{findFirst:vi.fn().mockResolvedValue({id:'p',tenantId:actor.tenantId,status:'DRAFT',approvalStatus:'PENDING_REVIEW',submittedById:'another-user',packages:[]})},$transaction:vi.fn((run:any)=>run(tx))};await new AdminWorkspaceService(p).reviewPromotion(actor,'p',{action:'REJECT',note:'  Harga belum sesuai  '});expect(tx.promotion.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({reviewNote:'Harga belum sesuai'})}))});
  it('does not let a content manager approve without content.approve',async()=>{const actor=identity('content.manage'),p:any={promotion:{findFirst:vi.fn().mockResolvedValue({id:'p',tenantId:actor.tenantId,status:'DRAFT',approvalStatus:'PENDING_REVIEW',submittedById:'another-user',packages:[]})}};await expect(new AdminWorkspaceService(p).reviewPromotion(actor,'p',{action:'APPROVE'})).rejects.toThrow(/content\.approve/)});
  it('rejects package ids that are not all owned by the current tenant',async()=>{const actor=identity('content.manage','content.approve'),p:any={travelPackage:{findMany:vi.fn().mockResolvedValue([])}};await expect(new AdminWorkspaceService(p).createPromotion(actor,{code:'PROMO-1',title:'Promo',discountType:'PERCENTAGE',discountValue:10,startsAt:'2026-09-01T00:00:00Z',endsAt:'2026-10-01T00:00:00Z',packageIds:['30000000-0000-4000-8000-000000000001']})).rejects.toThrow(/tenant/)});
});

describe('package review contract',()=>{
  const pending={id:'package-a',tenantId:baseIdentity.tenantId,status:'DRAFT',approvalStatus:'PENDING_REVIEW'};
  it('requires a rejection note',async()=>{const p:any={travelPackage:{findFirst:vi.fn().mockResolvedValue(pending)}};await expect(new AdminWorkspaceService(p).reviewPackage(identity('package.approve'),'package-a',{action:'REJECT'})).rejects.toThrow(/Catatan wajib/)});
  it('allows a least-privilege package approver to reject and trims the note',async()=>{const tx:any={travelPackage:{update:vi.fn().mockResolvedValue({...pending,approvalStatus:'REJECTED'})},auditLog:{create:vi.fn()}},p:any={travelPackage:{findFirst:vi.fn().mockResolvedValue(pending)},$transaction:vi.fn((run:any)=>run(tx))};await new AdminWorkspaceService(p).reviewPackage(identity('package.approve'),'package-a',{action:'REJECT',note:'  Itinerary belum lengkap  '});expect(tx.travelPackage.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({reviewNote:'Itinerary belum lengkap'})}))});
  it('clears the previous review decision when a rejected package is resubmitted',async()=>{const tx:any={travelPackage:{update:vi.fn().mockResolvedValue({...pending,approvalStatus:'PENDING_REVIEW'})},auditLog:{create:vi.fn()}},p:any={travelPackage:{findFirst:vi.fn().mockResolvedValue({...pending,approvalStatus:'REJECTED',reviewedById:'reviewer-a',reviewedAt:new Date(),reviewNote:'Perbaiki itinerary'})},$transaction:vi.fn((run:any)=>run(tx))};await new AdminWorkspaceService(p).reviewPackage(identity('package.update'),'package-a',{action:'SUBMIT'});expect(tx.travelPackage.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({approvalStatus:'PENDING_REVIEW',reviewedById:null,reviewedAt:null,reviewNote:null})}))});
  it('requires package.update to submit a package',async()=>{const p:any={travelPackage:{findFirst:vi.fn().mockResolvedValue({...pending,approvalStatus:'DRAFT'})}};await expect(new AdminWorkspaceService(p).reviewPackage(identity('package.read'),'package-a',{action:'SUBMIT'})).rejects.toThrow(/package\.update/)});
});

describe('permission-aware dashboard',()=>{
  it('does not query or return task and trip data without their read permissions',async()=>{const p:any={lead:{count:vi.fn()},customer:{count:vi.fn()},booking:{count:vi.fn()},invoice:{aggregate:vi.fn()},task:{findMany:vi.fn()},trip:{findMany:vi.fn()}};const result=await new AdminWorkspaceService(p).dashboard(identity());expect(result.myTasks).toEqual([]);expect(result.myTrips).toEqual([]);expect(p.task.findMany).not.toHaveBeenCalled();expect(p.trip.findMany).not.toHaveBeenCalled()});
});
