'use client';
import {FormEvent,useEffect,useState}from'react';
import{apiGet,apiPatch,apiPost}from'../lib/api';

type Row={id:string;[key:string]:any};
type PageResult<T>={items:T[];meta:{page:number;pageSize:number;total:number;totalPages:number}};
type Config={title:string;eyebrow:string;description:string;endpoint:string;permission:string;fields:{name:string;label:string;type?:string;required?:boolean;options?:string[]}[];render:(x:Row)=>React.ReactNode};
function Workspace({config}:{config:Config}){const[rows,setRows]=useState<Row[]>([]),[msg,setMsg]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[meta,setMeta]=useState({page:1,pageSize:20,total:0,totalPages:1});const load=()=>apiGet<PageResult<Row>>(`${config.endpoint}?page=${page}&pageSize=20&search=${encodeURIComponent(search)}`).then(x=>{setRows(x.items);setMeta(x.meta);setMsg('')}).catch(e=>setMsg((e as Error).message));useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[config.endpoint,page,search]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body:Record<string,FormDataEntryValue>=Object.fromEntries(f.entries());try{await apiPost(config.endpoint,body);e.currentTarget.reset();setMsg('Berhasil disimpan.');setPage(1);await load()}catch(x){setMsg((x as Error).message)}}
return <main className="modulePage adminWorkspace"><div className="moduleHeading"><div><p>{config.eyebrow}</p><h1>{config.title}</h1><span>{config.description}</span></div><b>{meta.total} data</b></div><details className="createPanel"><summary>＋ Tambah data</summary><form className="moduleForm" onSubmit={submit}>{config.fields.map(f=><label key={f.name}>{f.label}{f.options?<select name={f.name} required={f.required}>{f.options.map(o=><option key={o}>{o}</option>)}</select>:f.type==='textarea'?<textarea name={f.name} required={f.required}/>:<input name={f.name} type={f.type||'text'} required={f.required}/>}</label>)}<button className="primary">Simpan</button></form></details><div className="crmToolbar"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder={`Cari ${config.title.toLowerCase()}…`}/></div>{msg&&<p className="moduleNotice">{msg}</p>}<section className="workspaceCards">{rows.map(x=><article key={x.id}>{config.render(x)}</article>)}{!rows.length&&!msg&&<p className="empty">Belum ada data.</p>}</section><div className="paginationBar"><button disabled={page<=1} onClick={()=>setPage(x=>x-1)}>Sebelumnya</button><span>Halaman {meta.page} dari {meta.totalPages}</span><button disabled={page>=meta.totalPages} onClick={()=>setPage(x=>x+1)}>Berikutnya</button></div></main>}

export function ContentWorkspace(){return <Workspace config={{title:'Content Studio',eyebrow:'WEBSITE CONTENT',description:'Tulis, simpan draft, dan terbitkan artikel dari satu tempat.',endpoint:'/content/articles',permission:'content.manage',fields:[{name:'title',label:'Judul',required:true},{name:'slug',label:'Slug URL',required:true},{name:'excerpt',label:'Ringkasan',type:'textarea'},{name:'content',label:'Isi artikel',type:'textarea',required:true},{name:'coverImage',label:'URL cover'},{name:'status',label:'Status',options:['DRAFT','PUBLISHED']}],render:x=><><small>{x.status} · /articles/{x.slug}</small><h2>{x.title}</h2><p>{x.excerpt||'Tanpa ringkasan'}</p></>}}/>}
export function MediaWorkspace(){return <Workspace config={{title:'Media Library',eyebrow:'WEBSITE MEDIA',description:'Daftarkan gambar dan dokumen yang sudah diunggah ke storage/CDN.',endpoint:'/media',permission:'content.manage',fields:[{name:'originalName',label:'Nama file',required:true},{name:'url',label:'URL publik',type:'url',required:true},{name:'mimeType',label:'MIME type'},{name:'altText',label:'Alt text'},{name:'category',label:'Kategori'}],render:x=><><small>{x.category} · {x.mimeType}</small><h2>{x.originalName}</h2><a href={x.url} target="_blank" rel="noreferrer">Buka media →</a></>}}/>}
export function AssetKnowledgeWorkspace(){return <main className="modulePage"><div className="moduleHeading"><div><p>INTERNAL RESOURCES</p><h1>Asset & Knowledge</h1><span>Inventaris tim dan pengetahuan operasional dalam satu ruang kerja.</span></div></div><div className="workspaceSplit"><Workspace config={{title:'Asset Tim',eyebrow:'ASSET',description:'Peralatan operasional dan penugasannya.',endpoint:'/assets',permission:'asset.manage',fields:[{name:'assetCode',label:'Kode asset',required:true},{name:'name',label:'Nama asset',required:true},{name:'category',label:'Kategori',required:true},{name:'brand',label:'Merek'},{name:'serialNumber',label:'Serial number'},{name:'location',label:'Lokasi'}],render:x=><><small>{x.assetCode} · {x.status}</small><h2>{x.name}</h2><p>{x.category} · {x.location||'-'}</p></>}}/><Workspace config={{title:'Knowledge Base',eyebrow:'SOP & KNOWLEDGE',description:'SOP, panduan, dan catatan operasional.',endpoint:'/knowledge',permission:'knowledge.manage',fields:[{name:'title',label:'Judul',required:true},{name:'category',label:'Kategori',required:true},{name:'summary',label:'Ringkasan',type:'textarea'},{name:'content',label:'Isi dokumen',type:'textarea',required:true},{name:'status',label:'Status',options:['DRAFT','PUBLISHED']}],render:x=><><small>{x.category} · v{x.version} · {x.status}</small><h2>{x.title}</h2><p>{x.summary}</p></>}}/></div></main>}
export function ArchiveWorkspace(){return <Workspace config={{title:'Arsip Dokumen',eyebrow:'FILE ARCHIVE',description:'Simpan referensi dokumen booking, invoice, trip, kontrak, dan legal.',endpoint:'/archives',permission:'archive.manage',fields:[{name:'title',label:'Judul',required:true},{name:'category',label:'Kategori',options:['QUOTATION','BOOKING','INVOICE','PAYMENT','CUSTOMER','EMPLOYEE','CONTRACT','PROJECT','TRIP','PACKAGE','LEGAL','OTHER']},{name:'fileName',label:'Nama file',required:true},{name:'fileUrl',label:'URL file',type:'url',required:true},{name:'documentDate',label:'Tanggal dokumen',type:'date'},{name:'expiresAt',label:'Berlaku sampai',type:'date'},{name:'tags',label:'Tag'},{name:'notes',label:'Catatan',type:'textarea'}],render:x=><><small>{x.category} · {x.status}</small><h2>{x.title}</h2><p>{x.fileName}</p><a href={x.fileUrl} target="_blank" rel="noreferrer">Buka dokumen →</a></>}}/>}

export function PackageReviewWorkspace(){const[rows,setRows]=useState<Row[]>([]),[msg,setMsg]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[meta,setMeta]=useState({page:1,pageSize:20,total:0,totalPages:1});const load=()=>apiGet<PageResult<Row>>(`/package-reviews?page=${page}&pageSize=20&search=${encodeURIComponent(search)}`).then(x=>{setRows(x.items);setMeta(x.meta);setMsg('')}).catch(e=>setMsg((e as Error).message));useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[page,search]);async function act(id:string,action:string){try{await apiPatch('/package-reviews/'+id,{action});await load()}catch(e){setMsg((e as Error).message)}}return <main className="modulePage"><div className="moduleHeading"><div><p>QUALITY GATE</p><h1>Review Paket</h1><span>Konten paket harus ditinjau sebelum aktif di website dan POS.</span></div><b>{meta.total} data</b></div><div className="crmToolbar"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Cari paket…"/></div>{msg&&<p className="moduleNotice">{msg}</p>}<section className="workspaceCards">{rows.map(x=><article key={x.id}><small>{String(x.packageCode)} · {String(x.approvalStatus)}</small><h2>{String(x.name)}</h2><p>Status katalog: {String(x.status)}</p><div className="bookingActions">{x.approvalStatus==='DRAFT'&&<button onClick={()=>act(x.id,'SUBMIT')}>Ajukan review</button>}{x.approvalStatus==='PENDING_REVIEW'&&<><button className="primary" onClick={()=>act(x.id,'APPROVE')}>Setujui</button><button onClick={()=>act(x.id,'REJECT')}>Tolak</button></>}</div></article>)}</section><div className="paginationBar"><button disabled={page<=1} onClick={()=>setPage(x=>x-1)}>Sebelumnya</button><span>Halaman {meta.page} dari {meta.totalPages}</span><button disabled={page>=meta.totalPages} onClick={()=>setPage(x=>x+1)}>Berikutnya</button></div></main>}
