'use client';
import {FormEvent,useEffect,useState} from'react';
import{apiGet,apiPatch,apiPost}from'../lib/api';
type Pack={id:string;name:string;status:string;approvalStatus:string};type Promo={id:string;code:string;title:string;description?:string;status:string;approvalStatus:string;reviewNote?:string;packages:{package:Pack}[]};type Page<T>={items:T[];meta:{total:number}};
export function PromotionManagement(){
  const[rows,setRows]=useState<Promo[]>([]),[packs,setPacks]=useState<Pack[]>([]),[permissions,setPermissions]=useState<string[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
  const can=(permission:string)=>permissions.includes(permission);
  const canManage=can('content.manage')&&can('package.read');
  const load=()=>Promise.all([apiGet<Page<Promo>>('/content/promotions?pageSize=100'),apiGet<{permissions:string[]}>('/auth/me')]).then(async([promotions,identity])=>{setRows(promotions.items);setPermissions(identity.permissions);if(identity.permissions.includes('content.manage')&&identity.permissions.includes('package.read')){const packages=await apiGet<Page<Pack>>('/packages?pageSize=100');setPacks(packages.items.filter(x=>x.status==='ACTIVE'&&x.approvalStatus==='APPROVED'))}else setPacks([]);setMsg('')}).catch(e=>setMsg((e as Error).message));
  useEffect(()=>{void load()},[]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await apiPost('/content/promotions',{code:String(f.get('code')||'').trim().toUpperCase(),title:String(f.get('title')||''),description:String(f.get('description')||''),discountType:String(f.get('discountType')),discountValue:Number(f.get('discountValue')),startsAt:new Date(String(f.get('startsAt'))).toISOString(),endsAt:new Date(String(f.get('endsAt'))).toISOString(),packageIds:f.getAll('packageIds')});e.currentTarget.reset();await load()}catch(error){setMsg((error as Error).message)}finally{setBusy(false)}}
  async function act(id:string,action:'SUBMIT'|'APPROVE'|'REJECT'|'ARCHIVE'){const note=action==='REJECT'?window.prompt('Alasan penolakan')?.trim():undefined;if(action==='REJECT'&&!note)return;setBusy(true);try{await apiPatch(`/content/promotions/${id}/review`,{action,note});await load()}catch(error){setMsg((error as Error).message)}finally{setBusy(false)}}
  return <main className="modulePage"><div className="moduleHeading"><div><p>WEBSITE COMMERCE</p><h1>Promotion Management</h1><span>Promo tidak tayang sebelum paket dan kontennya ditinjau.</span></div><b>{rows.length} promo</b></div>{msg&&<p className="moduleNotice">{msg}</p>}{canManage&&<section className="panel"><h2>Buat promo draft</h2><form className="workspaceForm" onSubmit={create}><label>Kode<input name="code" required pattern="[A-Za-z0-9-]{2,40}"/></label><label>Judul<input name="title" required maxLength={180}/></label><label>Jenis<select name="discountType"><option value="PERCENTAGE">Persentase</option><option value="FIXED_AMOUNT">Nominal</option></select></label><label>Nilai<input name="discountValue" type="number" min="0.01" step="0.01" required/></label><label>Mulai<input name="startsAt" type="datetime-local" required/></label><label>Selesai<input name="endsAt" type="datetime-local" required/></label><label>Deskripsi<textarea name="description"/></label><fieldset><legend>Paket publik</legend>{packs.map(x=><label key={x.id}><input type="checkbox" name="packageIds" value={x.id}/>{x.name}</label>)}</fieldset><button className="primary" disabled={busy||!packs.length}>Simpan draft</button></form></section>}<section className="workspaceCards">{rows.map(x=><article key={x.id}><small>{x.code} · {x.status} / {x.approvalStatus}</small><h2>{x.title}</h2><p>{x.description||'Tanpa deskripsi'}</p><p>{x.packages.map(p=>p.package.name).join(', ')||'Belum ada paket'}</p>{x.reviewNote&&<p>Catatan review: {x.reviewNote}</p>}<div className="bookingActions">{can('content.manage')&&['DRAFT','REJECTED'].includes(x.approvalStatus)&&x.status!=='ARCHIVED'&&<button disabled={busy} onClick={()=>act(x.id,'SUBMIT')}>Ajukan review</button>}{can('content.approve')&&x.approvalStatus==='PENDING_REVIEW'&&<><button className="primary" disabled={busy} onClick={()=>act(x.id,'APPROVE')}>Setujui & tayangkan</button><button disabled={busy} onClick={()=>act(x.id,'REJECT')}>Tolak</button></>}{can('content.manage')&&x.status!=='ARCHIVED'&&<button disabled={busy} onClick={()=>act(x.id,'ARCHIVE')}>Arsipkan</button>}{!can('content.manage')&&!can('content.approve')&&<small>Mode baca saja</small>}</div></article>)}</section></main>
}
